services:
  wordle_api:
    image: "${IMAGE_NAME_API}-dev:${IMAGE_TAG_API}"
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 5678:5678
    env_file:
      - .env
    environment:
      - ENV=dev
    volumes:
      - ./backend:/app

  wordle_web:
    image: "${IMAGE_NAME_WEB}-dev:${IMAGE_TAG_WEB}"
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
