services:
  wordle_api:
    build: 
      args:
        - ENV_TYPE=dev
    ports:
      - 5678:5678
    env_file:
      - .env
    environment:
      - ENV=dev

  wordle_web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
