services:
  db_postgres:
    image: postgres:16
    container_name: ${CONTAINER_NAME_DB}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
  
  wordle_api:
    image: ${IMAGE_NAME_API}:${IMAGE_TAG_API}
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: ${CONTAINER_NAME_API}
    restart: always
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  wordle_web:
    image: ${IMAGE_NAME_WEB}:${IMAGE_TAG_WEB}
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: ${CONTAINER_NAME_WEB}
    restart: always
    depends_on:
      - wordle_api
    ports:
      - "8080:80"
    

volumes:
  db-postgres:
    driver: local
