"""fix game deletion cascade

Revision ID: a0949fde6af2
Revises: d52f4de98631
Create Date: 2024-04-27 20:11:10.882232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0949fde6af2'
down_revision: Union[str, None] = 'd52f4de98631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guess_game_id_fkey', 'guess', type_='foreignkey')
    op.create_foreign_key(None, 'guess', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guess', type_='foreignkey')
    op.create_foreign_key('guess_game_id_fkey', 'guess', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###
